/******************************************************
 * SIMON SAYS GAME - CORE GAME LOGIC
 * ----------------------------------------------------
 * gameSeq  -> Stores the sequence generated by the game
 * userSeq  -> Stores the sequence entered by the user
 * btns     -> Available button colors
 * started  -> Indicates whether the game has started
 * lvl      -> Tracks the current level
 ******************************************************/

let gameSeq = [];
let userSeq = [];

let btns = ["red", "green", "yellow", "blue"];
let started = false;
let lvl = 0;

// Reference to the heading used for level & game messages
let h2 = document.querySelector('h2');

/******************************************************
 * GAME START HANDLER
 * ----------------------------------------------------
 * Starts the game on first keypress.
 * Prevents restarting while the game is already running.
 ******************************************************/
document.addEventListener('keypress', function () {
    if (started === false) {
        console.log("Game Started");
        started = true;
        levelUp();
    }
});

/******************************************************
 * BUTTON FLASH (GAME SEQUENCE)
 * ----------------------------------------------------
 * Visually flashes a button selected by the game
 ******************************************************/
function btnFlash(btn) {
    btn.classList.add("flash");

    setTimeout(function () {
        btn.classList.remove("flash");
    }, 250);
}

/******************************************************
 * BUTTON FLASH (USER INPUT)
 * ----------------------------------------------------
 * Visually flashes a button clicked by the user
 ******************************************************/
function userFlash(btn) {
    btn.classList.add("user-flash");

    setTimeout(function () {
        btn.classList.remove("user-flash");
    }, 250);
}

/******************************************************
 * LEVEL UP LOGIC
 * ----------------------------------------------------
 * - Resets user input for the new level
 * - Increments level count
 * - Generates a new random color
 * - Updates and displays the game sequence
 ******************************************************/
function levelUp() {
    // Reset user sequence for the new level
    userSeq = [];

    // Increase level count
    lvl++;
    h2.innerText = `Level ${lvl}`;

    // Generate a random index for button selection
    let randIdx = Math.floor(Math.random() * 4);
    let randColor = btns[randIdx];

    // Select the corresponding button
    let randBtn = document.querySelector(`.${randColor}`);

    // Add color to game sequence
    gameSeq.push(randColor);

    // Flash the selected button
    btnFlash(randBtn);
}

/******************************************************
 * ANSWER VALIDATION LOGIC
 * ----------------------------------------------------
 * Checks the user's latest input against the game sequence
 * - Correct input -> continue
 * - Full correct sequence -> next level
 * - Wrong input -> game over
 ******************************************************/
function checkAns(idx) {
    // Check only the most recent input
    if (gameSeq[idx] === userSeq[idx]) {

        // If user has completed the full sequence correctly
        if (userSeq.length === gameSeq.length) {
            setTimeout(levelUp, 1000);
        }

    } else {
        // Game Over state
        h2.innerHTML = `GAME OVER ! Your Score <b>${lvl}</b> <br> Press any key to Start`;

        // Visual feedback for wrong input
        document.querySelector('body').style.backgroundColor = "red";

        setTimeout(function () {
            document.querySelector('body').style.backgroundColor = "white";
        }, 200);

        // Reset game state
        reset();
    }
}

/******************************************************
 * RESET GAME STATE
 * ----------------------------------------------------
 * Brings the game back to initial state
 ******************************************************/
function reset() {
    started = false;
    gameSeq = [];
    userSeq = [];
    lvl = 0;
}

/******************************************************
 * USER BUTTON PRESS HANDLER
 * ----------------------------------------------------
 * - Detects which button was clicked
 * - Stores user input
 * - Triggers answer validation
 ******************************************************/
function btnPress() {
    let currBtn = this;

    // Flash user-selected button
    userFlash(currBtn);

    // Get color of clicked button
    let userColor = currBtn.getAttribute("id");

    // Store user input
    userSeq.push(userColor);

    // Validate the latest input
    checkAns(userSeq.length - 1);
}

/******************************************************
 * ATTACH CLICK EVENTS TO ALL BUTTONS
 ******************************************************/
let allBtns = document.querySelectorAll(".btn");

for (let btn of allBtns) {
    btn.addEventListener("click", btnPress);
}
